jobs:      
  - name: dv-run-sh
    type: runSh
    steps:
      - IN: dv-params-1
      - TASK:
        - script: printenv
        - script: cat $META/integration.json
        - script: shipctl get_json_value $META/integration.json
