jobs:      
  - name: dv-run-sh
    type: runSh
    steps:
      - IN: dv-params-1
      - TASK:
        - script: terraform --version
        - script: kubectl version
        - script: jfrog --version
        - script: gcloud --version
        - script: eb --version
        - script: packer --version
        - script: az --version
        - script: yarn --version
        
        
